POST http://localhost:3333/events
Content-Type: application/json

{
  "title": 123, 
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/66df5ae6-1cf1-4563-9f7b-2fd242a2f82e/attendees
Content-Type: application/json

{
  "name": "Diego",
  "email": "Diego@teste.com"
}

###

GET http://localhost:3333/events/66df5ae6-1cf1-4563-9f7b-2fd242a2f82e

###

GET http://localhost:3333/attendees/8/badge

###

GET http://localhost:3333/attendees/6/check-in

###
GET http://localhost:3333/events/66df5ae6-1cf1-4563-9f7b-2fd242a2f82e/attendees?query=diego